fruits=["apple", "banana", "cherry", "kiwi"]
fruits.append("orange")
print(fruits)
print("---------")
print("---------")
print("---------")
fruits.insert(1, "grape")
print(fruits)
print("---------")
fruits.remove("kiwi")
print(fruits)
print("---------")
print("---------")
fruits.pop()
print(fruits)